### ISSUE TITLE
Getting error logs for invalid function calls

### ISSUE THREAD

**Issue by tleyden** [toshiapp/toshi-app-js#32]
I accidentally called a non-existent function from one of my functions:

```
function welcome(session) {
  nonExistentFunction(...)
}
```

and there weren't any errors on the console.

```
bot_1              | [I] Headless client ready...
bot_1              | [D] handling websocket message: {"result": true, "jsonrpc": "2.0", "id": 1}
bot_1              | [I] ⇒  Received 'Message' from @user92111
bot_1              | [I] ⇒  Hey
bot_1              |
bot_1              |
```

I tried changing the `docker-compose.yml` to:

```
      - LOG_LEVEL=DEBUG
```

but that didn't help either.  

Any tips on how to get better error messages for this class of errors?  Are there any node.js config options or function handlers for this?

**Comment by tleyden** [comment]
Based on https://gist.github.com/balupton/5560110#file-trycatch-js, this worked for me:

```
  try {
	  // the synchronous code that we want to catch thrown errors on
	  // var err = new Error('example');
    // throw err;

    switch (message.type) {
      case 'Init':
        welcome(session)
        break
      case 'Message':
        onMessage(session, message)
        break
      ...
    }
    
  
  } catch (err) {
	  // handle the error safely
	  console.log(err);
  }
```

It shows this error in the docker compose logs:

```
bot_1              | onEvent() called
bot_1              | ReferenceError: sendDefaultMessages is not defined
bot_1              |     at welcome (/usr/src/bot/src/bot.js:103:5)
bot_1              |     at onMessage (/usr/src/bot/src/bot.js:51:3)
bot_1              |     at Bot.bot.onEvent (/usr/src/bot/src/bot.js:23:9)
bot_1              |     at Bot.onClientMessage (/usr/src/bot/src/lib/Bot.js:32:12)
bot_1              |     at Session (/usr/src/bot/src/lib/Client.js:94:26)
bot_1              |     at IdService.getUser.then (/usr/src/bot/src/lib/Session.js:167:13)
bot_1              |     at <anonymous>
bot_1              |     at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by faymontage** [comment]
@tleyden I've made some quick fixes to the logging that should prevent this https://github.com/toshiapp/toshi-app-js/commit/e57447934b9d9c01d7ba2031ecdeaf0ae88b35c3
